reclamation_homepage:
    path:     /
    defaults: { _controller: ReclamationBundle:Default:index }
#reclamation_addRec:
#    path:     /addRec
#    defaults: { _controller: ReclamationBundle:Reclamation:addRec }
