security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    access_denied_url: /login

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        SCRUM_MASTER:   SCRUM_MASTER
        PRODUCT_OWNER: PRODUCT_OWNER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            user_checker: security.user_checker
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true
            logout_on_user_change: true
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, role: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/, role: ROLE_USER  }
        - { path: ^/admin$, role: ROLE_ADMIN }