<?php

namespace ActiviteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PresenceReunionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresenceReunionRepository extends EntityRepository
{

}
